version: '3.9'
services:
  api:
    container_name: food_order_api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 9000:8080
    environment:
      - MONGO_URI=mongodb://mongo-container/nodejs
    networks:
      - b
    depends_on:
      - mongo-container

  mongo-container:
    image: mongo
    restart: always
    container_name: mongo-container
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./.docker/mongodb:/data/db
    networks:
      - b

networks:
  b:
    name: b-network
